# Generated by Django 5.1 on 2024-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_checkoutclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutclass',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
