# Generated by Django 5.1 on 2024-10-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0003_productclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='productimage4',
            field=models.ImageField(blank=True, null=True, upload_to='productpictures'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='productimage5',
            field=models.ImageField(blank=True, null=True, upload_to='productpictures'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='productimage6',
            field=models.ImageField(blank=True, null=True, upload_to='productpictures'),
        ),
    ]
