# Generated by Django 5.1 on 2024-10-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0004_productclass_productimage4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='productimage4',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='productimage5',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='productimage6',
        ),
    ]
